name: CI/CD test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libboost-dev libgtest-dev valgrind lcov
    
    - name: Build with coverage
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON ..
        make -j$(nproc)
        find . -name "*.gcno" -exec echo "Generated gcno: {}" \;

    - name: Run tests (for coverage)
      run: |
        cd build
        ctest --output-on-failure
        find . -name "*.gcda" -exec echo "Generated gcda: {}" \;

    - name: Generate coverage report
      run: |
        cd build
        lcov --capture --directory . --output-file coverage.info --ignore-errors mismatch,empty
        lcov --remove coverage.info '/usr/*' '*/tests/*' --output-file coverage.info
        lcov --list coverage.info

    - name: Valgrind memory check
      run: |
        cd build
        valgrind --leak-check=full --error-exitcode=1 ./bin/TrafficMonitoringTests
        